version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.5.5'
    restart: always
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - my-dse-network
    volumes:
      - zookeeper_data:/bitnami/zookeeper
  kafka:
    image: 'bitnami/kafka:2.2.1'
    hostname: kafka
    container_name: kafka
    restart: always
    ports:
      - '9092:9092'
      - '9093:9093'
    networks:
      - my-dse-network
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9093,EXTERNAL://mydockerhost:9092
      - KAFKA_CFG_LISTENERS=CLIENT://:9093,EXTERNAL://:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/bitnami/kafka
volumes:
  zookeeper_data:
  kafka_data:

networks:
  my-dse-network:
    name: my-dse-network

